version: '3.7'

volumes:
  Ho-MinIOdata:

x-minio-common: &minio-common
  image: minio/minio
  command: server --console-address ":9090" /minio1/mnt/data
  ports:
    - "9000:9000"
    - "9090:9090"
  healthcheck:
    test: ["CMD", "curl", "-f", "https://minioapi.shomamamama.com:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    ports:
      - ":443"
    volumes:
      - type: bind
        source: /mnt/data/compose
        target: /mnt/data
      - type: bind
        source: /etc/default/minio
        target: /etc/config.env
      - Ho-MinIOdata:/minio1/mnt/data
      - ./certs:/certs:ro
    networks:
      - Ho

networks:
  Ho:
    external: true
