version: '3'

services:
  Taco-server:    
    image: taco:${IMAGE_TAG}
    container_name: taco
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
    expose:
      - 80
      - 443
    networks:
      - Ho
networks:
  Ho:
    external: true
