version: '3'

services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - Ho

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - ":8001"
      - ":443"
    environment:
      - REDISINSIGHT_REVERSE_PROXY=true
      - REDISINSIGHT_SERVER_NAME=redis.shomamamama.com
      - REDISINSIGHT_SERVER_SCHEME=https
      -e RIPROXYENABLE=true
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - Ho

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  Ho:
    external: true
