name: CD Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Images
        run: |
            cd ./Taco/
            docker-compose build

      - name: Extract Version Number
        id: extract_version
        run: echo "::set-output name=version::$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v\(.*\)/\1/p')"
    
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 159.65.199.5
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/HoHoHoo/Taco/
            docker-compose down
            git pull
            docker-compose up -d
            

          
      - name: Login to Harbor
        uses: appleboy/ssh-action@master
        with:
            host: 159.65.199.5
            username: "root"
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
                cd /root/HoHoHoo/Server/
                docker login harbor.shomamamama.com -u ${{ secrets.HARBOR_USER }} --password-stdin <<< ${{ secrets.HARBOR_PASS }}
            
      - name: Build and Tag Docker Image
        run: |
            version=${{ steps.extract_version.outputs.version }}
            docker login harbor.shomamamama.com -u ${{ secrets.HARBOR_USER }} --password-stdin <<< ${{ secrets.HARBOR_PASS }}
            cd ./Server/
            docker build -t harbor.shomamamama.com/hohohoo/ssl-server:${version} .
            docker tag harbor.shomamamama.com/hohohoo/ssl-server:${version} harbor.shomamamama.com/hohohoo/ssl-server:latest
            cd ../Taco/
            docker build -t harbor.shomamamama.com/hohohoo/taco:${version} .
            docker tag harbor.shomamamama.com/hohohoo/taco:${version} harbor.shomamamama.com/hohohoo/taco:latest
            
      - name: Push Image to Harbor
        run: |
            version=${{ steps.extract_version.outputs.version }}
            docker push harbor.shomamamama.com/hohohoo/taco:${version}
            docker push harbor.shomamamama.com/hohohoo/taco 
            
            docker push harbor.shomamamama.com/hohohoo/ssl-server:${version}
            docker push harbor.shomamamama.com/hohohoo/ssl-server 
