name: CD Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Images
        run: |
            cd ./Taco/
            docker-compose build
        #docker push <your-docker-registry>/<your-image-name>:v0.1.0

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 159.65.199.5
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/HoHoHoo/Taco/
            docker-compose down
            git pull
            docker-compose up -d
            
        # - name: Login to Harbor
        #   uses: appleboy/ssh-action@master
        #   with:
        #     host: 159.65.199.5
        #     username: "root"
        #     key: ${{ secrets.SSH_PRIVATE_KEY }}
        #     port: 22
        #     script: |
        #       cd /root/HoHoHoo/Server/
        #       docker login harbor.shomamamama.com -u ${{ secrets.HARBOR_USER }} --password-stdin <<< ${{ secrets.HARBOR_PASS }}
            
        # - name: Build and Tag Docker Image
        #   uses: appleboy/ssh-action@master
        #   with:
        #     host: 159.65.199.5
        #     username: "root"
        #     key: ${{ secrets.SSH_PRIVATE_KEY }}
        #     port: 22
        #     script: |
        #       docker build -t harbor.shomamamama.com/hohohoo/ssl-server:v0.1.0 .
        #       docker tag harbor.shomamamama.com/hohohoo/ssl-server:v0.1.0 harbor.shomamamama.com/hohohoo/ssl-server:latest
            
        # - name: Push Image to Harbor
        #   uses: appleboy/ssh-action@master
        #   with:
        #     host: 159.65.199.5
        #     username: "root"
        #     key: ${{ secrets.SSH_PRIVATE_KEY }}
        #     port: 22
        #     script: |
        #       docker push harbor.shomamamama.com/hohohoo/ssl-server:v0.1.0
        #       docker push harbor.shomamamama.com/hohohoo/ssl-server   
