name: CI Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
      
            - name: Build Docker Images and Run Docker Compose
              uses: appleboy/ssh-action@master
              with:
                host: 159.65.199.5
                username: "root"
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                  cd /root/HoHoHoo/Taco/
                  docker-compose down
                  docker rmi taco:v0.1.0
                  git pull
                  docker build -t taco:v0.1.0 .
                  docker-compose up -d
                  cd ../MinIO/
                  docker-compose up -d
                  cd ../Redis/
                  docker-compose up -d
                  cd ../Server/
                  docker build -t ssl-server:v0.1.0 .
                  docker-compose up -d 
            
            - name: Start Minio and Upload Object
              uses: appleboy/ssh-action@master
              with:
                  host: 159.65.199.5
                  username: "root"
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                    cd /root/HoHoHoo/MinIO/
                    python3 app.py

            - name: Test SSL for Domains
              run: |
                # Use a tool like OpenSSL to test SSL certificates
                openssl s_client -connect taco.shomamamama.com:443 -servername taco.shomamamama.com
                openssl s_client -connect harbor.shomamamama.com:443 -servername harbor.shomamamama.com
                openssl s_client -connect minio.shomamamama.com:443 -servername minio.shomamamama.com
                openssl s_client -connect minioapi.shomamamama.com:443 -servername minioapi.shomamamama.com
                openssl s_client -connect redis.shomamamama.com:443 -servername redis.shomamamama.com

          # - name: Clean Up
          #   uses: appleboy/ssh-action@master
          #   with:
          #     host: 159.65.199.5
          #     username: "root"
          #     key: ${{ secrets.SSH_PRIVATE_KEY }}
          #     port: 22
          #     script: |
          #       cd /root/HoHoHoo/Taco/
          #       docker-compose down
          #       cd ../MinIO/
          #       docker-compose down
          #       cd ../Server/
          #       docker-compose down
          #       exit
