name: Bump version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      # uses: appleboy/ssh-action@master
      # with:
      #     host: 146.190.26.15
      #     username: "root"
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     port: 22
          # script: |
          #   cd /root/HoHoHoo/
          #   git pull
          #   chmod +x ./entrypoint.sh
      uses: biighunter/HoHoHoo@main # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: false